-- ============================================================
-- TCC - Sistema de Monitoramento Inteligente de EPI
-- Banco de dados: PostgreSQL
-- Schema do MVP
-- ============================================================

-- Este arquivo cria apenas a estrutura do banco.
-- O banco em si deve existir antes da execução, por exemplo:
-- CREATE DATABASE tcc_ppe;
--
-- Depois, conectado ao banco tcc_ppe, execute este arquivo.

BEGIN;

-- ============================================================
-- 1. CAMERAS
-- ============================================================

CREATE TABLE IF NOT EXISTS cameras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(150),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cameras IS 'Câmeras cadastradas no sistema.';
COMMENT ON COLUMN cameras.code IS 'Identificador lógico da câmera, por exemplo camera_1.';

-- ============================================================
-- 2. EPIS
-- ============================================================

CREATE TABLE IF NOT EXISTS epis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE epis IS 'Catálogo de equipamentos de proteção individual monitorados.';

-- ============================================================
-- 3. EVENT_TYPES
-- ============================================================

CREATE TABLE IF NOT EXISTS event_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL,
    epi_id BIGINT NOT NULL,
    compliant BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_types_epi
        FOREIGN KEY (epi_id)
        REFERENCES epis (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE event_types IS 'Catálogo dos eventos observacionais gerados pela arquitetura de visão computacional.';
COMMENT ON COLUMN event_types.compliant IS 'Indica se o evento representa conformidade com o EPI associado.';

-- ============================================================
-- 4. RISK_AREAS
-- ============================================================

CREATE TABLE IF NOT EXISTS risk_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    x1 DOUBLE PRECISION NOT NULL,
    y1 DOUBLE PRECISION NOT NULL,
    x2 DOUBLE PRECISION NOT NULL,
    y2 DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_risk_areas_camera
        FOREIGN KEY (camera_id)
        REFERENCES cameras (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_risk_areas_camera_name
        UNIQUE (camera_id, name),

    CONSTRAINT ck_risk_areas_coordinates
        CHECK (x2 > x1 AND y2 > y1)
);

COMMENT ON TABLE risk_areas IS 'Áreas de risco configuradas para cada câmera.';
COMMENT ON COLUMN risk_areas.x1 IS 'Coordenada X inicial da área no sistema de referência do frame.';
COMMENT ON COLUMN risk_areas.y1 IS 'Coordenada Y inicial da área no sistema de referência do frame.';
COMMENT ON COLUMN risk_areas.x2 IS 'Coordenada X final da área no sistema de referência do frame.';
COMMENT ON COLUMN risk_areas.y2 IS 'Coordenada Y final da área no sistema de referência do frame.';

-- ============================================================
-- 5. OBSERVATION_BATCHES
-- ============================================================

CREATE TABLE IF NOT EXISTS observation_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id BIGINT NOT NULL,
    risk_area_id BIGINT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    model_name VARCHAR(100),
    model_version VARCHAR(100),
    raw_detections JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_observation_batches_camera
        FOREIGN KEY (camera_id)
        REFERENCES cameras (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_observation_batches_risk_area
        FOREIGN KEY (risk_area_id)
        REFERENCES risk_areas (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE observation_batches IS 'Agrupador de uma execução do processamento observacional, normalmente associada a uma chamada do on_detect_all.';
COMMENT ON COLUMN observation_batches.received_at IS 'Momento em que o sistema recebeu/processou o conjunto de detecções. Não representa necessariamente o instante físico da captura.';
COMMENT ON COLUMN observation_batches.raw_detections IS 'Payload bruto recebido do modelo de visão computacional.';

-- ============================================================
-- 6. OBSERVATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    event_type_id BIGINT NOT NULL,
    person_ref INTEGER NOT NULL,
    context VARCHAR(20) NOT NULL,
    event_confidence DOUBLE PRECISION NOT NULL,
    conf_pessoa DOUBLE PRECISION NOT NULL,
    conf_epi DOUBLE PRECISION,

    person_bbox_x1 DOUBLE PRECISION,
    person_bbox_y1 DOUBLE PRECISION,
    person_bbox_x2 DOUBLE PRECISION,
    person_bbox_y2 DOUBLE PRECISION,

    epi_bbox_x1 DOUBLE PRECISION,
    epi_bbox_y1 DOUBLE PRECISION,
    epi_bbox_x2 DOUBLE PRECISION,
    epi_bbox_y2 DOUBLE PRECISION,

    source VARCHAR(50) NOT NULL DEFAULT 'visao_computacional',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_observations_batch
        FOREIGN KEY (batch_id)
        REFERENCES observation_batches (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_observations_event_type
        FOREIGN KEY (event_type_id)
        REFERENCES event_types (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_observations_person_ref
        CHECK (person_ref >= 0),

    CONSTRAINT ck_observations_event_confidence
        CHECK (event_confidence >= 0 AND event_confidence <= 1),

    CONSTRAINT ck_observations_conf_pessoa
        CHECK (conf_pessoa >= 0 AND conf_pessoa <= 1),

    CONSTRAINT ck_observations_conf_epi
        CHECK (conf_epi IS NULL OR (conf_epi >= 0 AND conf_epi <= 1)),

    CONSTRAINT ck_observations_context
        CHECK (context IN ('inside', 'outside', 'no_area', 'indeterminate')),

    CONSTRAINT ck_observations_person_bbox
        CHECK (
            (person_bbox_x1 IS NULL AND person_bbox_y1 IS NULL AND person_bbox_x2 IS NULL AND person_bbox_y2 IS NULL)
            OR
            (person_bbox_x1 IS NOT NULL AND person_bbox_y1 IS NOT NULL AND person_bbox_x2 IS NOT NULL AND person_bbox_y2 IS NOT NULL
             AND person_bbox_x2 > person_bbox_x1
             AND person_bbox_y2 > person_bbox_y1)
        ),

    CONSTRAINT ck_observations_epi_bbox
        CHECK (
            (epi_bbox_x1 IS NULL AND epi_bbox_y1 IS NULL AND epi_bbox_x2 IS NULL AND epi_bbox_y2 IS NULL)
            OR
            (epi_bbox_x1 IS NOT NULL AND epi_bbox_y1 IS NOT NULL AND epi_bbox_x2 IS NOT NULL AND epi_bbox_y2 IS NOT NULL
             AND epi_bbox_x2 > epi_bbox_x1
             AND epi_bbox_y2 > epi_bbox_y1)
        )
);

COMMENT ON TABLE observations IS 'Conclusões observacionais de conformidade de EPI geradas pela integração de visão computacional.';
COMMENT ON COLUMN observations.person_ref IS 'Índice efêmero da pessoa dentro do processamento; não representa uma identidade persistente.';
COMMENT ON COLUMN observations.event_confidence IS 'Confiança do evento observacional gerado pela arquitetura.';
COMMENT ON COLUMN observations.conf_pessoa IS 'Confiança da detecção da pessoa.';
COMMENT ON COLUMN observations.conf_epi IS 'Confiança do EPI associado, quando aplicável.';
COMMENT ON COLUMN observations.context IS 'Contexto espacial utilizado na interpretação da observação.';
COMMENT ON COLUMN observations.source IS 'Origem lógica do registro, atualmente visao_computacional.';

-- ============================================================
-- 5. IMAGE_EVIDENCE
-- ============================================================
CREATE TABLE IF NOT EXISTS image_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT NOT NULL
        REFERENCES observations(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    camera_code VARCHAR(50) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    image_path VARCHAR(1024) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE image_evidence IS 'Evidências de imagem associadas a uma ocorrência observacional.';
COMMENT ON COLUMN image_evidence.occurrence_id IS 'FK para observations.id (uma ocorrência pode ter várias evidências).';
COMMENT ON COLUMN image_evidence.camera_code IS 'Código lógico da câmera responsável pela captura.';
COMMENT ON COLUMN image_evidence.mime_type IS 'MIME oficial do arquivo persistido.';
COMMENT ON COLUMN image_evidence.file_name IS 'Último nome de arquivo salvo em data/images.';
COMMENT ON COLUMN image_evidence.sha256 IS 'Soma de verificação do arquivo persistido.';
COMMENT ON COLUMN image_evidence.image_path IS 'Caminho absoluto/relativo armazenado para recuperação.';
COMMENT ON COLUMN image_evidence.created_at IS 'Hora de persistência do registro.';

-- ============================================================
-- ÍNDICES
-- ============================================================

-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_observation_batches_camera_received
    ON observation_batches (camera_id, received_at DESC);

CREATE INDEX IF NOT EXISTS idx_observation_batches_risk_area
    ON observation_batches (risk_area_id);

CREATE INDEX IF NOT EXISTS idx_observations_batch
    ON observations (batch_id);

CREATE INDEX IF NOT EXISTS idx_observations_event_type
    ON observations (event_type_id);

CREATE INDEX IF NOT EXISTS idx_observations_created_at
    ON observations (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_observations_event_created
    ON observations (event_type_id, created_at DESC);

COMMIT;
