name: Monitoramento com visao computacional  com mais cameras v2
description: ""
ports:
- 9393
bricks:
- arduino:web_ui: {}
- arduino:video_object_detection:
    model: yolox-object-detection
    devices:
    - remote_camera_0
- arduino:telegram_bot:
    variables:
      TELEGRAM_BOT_TOKEN: 8671449367:AAHbDhM1__1WG1cvMFBzb_QrUCBCfF0QpHs
icon: 📸
